executor/flags.go, executor/linux/build.go, executor/linux/service.go, executor/linux/stage.go, executor/linux/step.go
The codecov checks are failing because this PR reduces the total number of LOC by using the `AppendData()` function. This reduction in LOC causes our % of test coverage to decrease.
I vote we ignore these checks because I'm not really reducing the % of test coverage 👍
=> refactor(linux): use AppendData() library.Log func

executor/linux/opts.go, executor/linux/service.go, executor/linux/step.go
This will help ensure steps with `detach: true` will still be updated properly 😄 
Currently, a step with `detach:true` will not have some of the fields populated.
=> fix(linux): update detached containers

executor/linux/secret.go, go.mod, go.sum
This PR will fix a bug that is stopping us from using the proper key when querying for a secret.
Dependent PR:
https://github.com/go-vela/types/pull/91
=> fix(secrets): use values from parse functions

go.mod, go.sum
See https://github.com/go-vela/pkg-runtime/pull/52 for more details
=> chore: update go-vela/pkg-runtime for host volumes

executor/linux/build.go, executor/linux/build_test.go, executor/linux/secret.go, executor/linux/secret_test.go, executor/linux/service.go, executor/linux/service_test.go, executor/linux/stage.go, executor/linux/step.go, executor/linux/step_test.go
This PR contains various bug fixes/enhancements to the following:
* Fail pipelines when you're unable to pull external secrets
* defer step/service log updates when streaming logs
* Only set build from running to success when the build has finished executing
=> fix(linux): update build status success at finish

executor/linux/secret.go, executor/linux/secret_test.go, go.mod, go.sum
Update for new types function:
https://github.com/go-vela/types/pull/96
=> fix: shared secrets can be in any org

executor/linux/build.go, executor/linux/step.go
Currently, we're seeing behavior from the worker where some of the logs that are supposed to be uploaded in the `init` step are skipped.
The `init` step itself is responsible for performing a number of actions before executing the pipeline like creating pipeline resources on the host, fetching secrets etc.
Most of these actions can be found marked with a `>` character in the logs:
```sh
> Inspecting runtime network...
> Inspecting runtime volume...
> Pulling secrets...
> Pulling service images...
> Pulling stage images...
> Pulling step images...
> Pulling secret images...
```
The specific actions we seem to be missing logs for are the `Pulling <resource> images...` sections 👍 
This PR adds a `defer` block to ensure we upload those logs to the `init` step.
=> fix: uploading image content in init logs

executor/local/api.go, executor/local/build.go, executor/local/doc.go, executor/local/local.go, executor/local/opts.go, executor/local/secret.go, executor/local/service.go, executor/local/stage.go, executor/local/step.go
This adds the "shell" of implementing a new `local` executor.
You'll note that all of these functions `return nil` (or `return nil, nil`) and this is intended for now.
I plan to get all the functions defined, even if they do nothing, and then I'll add the logic to them in subsequent PRs.
=> feat(executor): add shell for local pkg

Makefile, executor/linux/linux.go, executor/local/local.go, executor/local/local_test.go
This adds a `New()` function for used for instantiating the `local` executor client.
Also found in this PR is the removal of the `-race` flag for our `make` commands for testing the code.
You can find more information on this flag here:
https://golang.org/doc/articles/race_detector.html
The reason for removing this flag is because we do testing for `stages` in the executor.
`stages`, by nature, attempt to use the same variables since they run concurrently.
i.e. what `repo` the pipeline is being executed for, what `build` the pipeline is being executed for, etc.
=> feat: implement new local client

executor/local/local_test.go, executor/local/opts.go, executor/local/opts_test.go
This implements a set of functions for populating specific values in the `local` executor client.
The functions that are being implemented:
* `WithBuild()`
* `WithHostname()`
* `WithPipeline()`
* `WithRepo()`
* `WithRuntime()`
* `WithUser()`
* `WithVelaClient()`
Most, if not all, of these functions will be used to set specific information when we attempt to execute a build locally.
That being said, it's worth mentioning that some of these functions may end up getting removed in the future once more pieces of how a build will be ran locally are ironed out.
I'm replicating as much of the `linux` executor as I think we'll need initially so I can get a functional example up and running.
Once that's complete, I plan to go …
=> feat: add local client options

executor/local/service.go, executor/local/service_test.go
This implements a set of functions for dealing with `services` in the `local` executor client.
* `CreateService()`
* `PlanService()`
* `ExecService()`
* `StreamService()`
* `DestroyService()`
This is a stepping stone to getting the `local` executor fully implemented when trying to run a pipeline locally.
=> feat(local): add logic for handling services

executor/local/step.go, executor/local/step_test.go
This implements a set of functions for dealing with `steps` in the `local` executor client.
* `CreateStep()`
* `PlanStep()`
* `ExecStep()`
* `StreamStep()`
* `DestroyStep()`
This is a stepping stone to getting the `local` executor fully implemented when trying to run a pipeline locally.
=> feat(local): add logic for handling steps

internal/doc.go, internal/internal.go
Adding [an `internal` package that will contain common code](https://golang.org/doc/go1.4#internalpackages) for executor resources (i.e. `services`, `stages`, `steps` etc.)
Currently, we already have [a `linux` executor](https://github.com/go-vela/pkg-executor/tree/master/executor/linux) and I'm working on building [a `local` executor](https://github.com/go-vela/pkg-executor/tree/master/executor/local).
As I'm building the `local` executor, we have large chunks of code that are the same or very similar in the `linux` executor.
I'm continuing to duplicate these chunks of code in the `local` executor so I can get it functional ASAP.
But, as I find these chunks that are duplicative, I'd like to start adding them to the …
=> feat: add internal pkg structure

executor/local/stage.go, executor/local/stage_test.go
This implements a set of functions for dealing with `stages` in the `local` executor client.
* `CreateStage()`
* `PlanStage()`
* `ExecStage()`
* `DestroyStage()`
This is a stepping stone to getting the `local` executor fully implemented when trying to run a pipeline locally.
=> feat(local): add logic for handling stages

executor/executor.go, executor/executor_test.go, executor/setup.go, executor/setup_test.go
This implements a `Local()` function on the `executor.Setup` type for creating the `local` executor client:
https://github.com/go-vela/pkg-executor/blob/8c81b991f1ef65c0f3ce88f693a9736c30df6c25/executor/setup.go#L78-L95
Also, added logic to handle the `local` executor driver when calling the `executor.New()` function (creates a new executor):
https://github.com/go-vela/pkg-executor/blob/8c81b991f1ef65c0f3ce88f693a9736c30df6c25/executor/executor.go#L43-L48
=> feat(executor): add local setup

executor/linux/api.go
When I vendor from this repo on `master`, into the [go-vela/cli](https://github.com/go-vela/cli) repo and build the CLI with `make build`, I get the following:
```
../../../../go/pkg/mod/github.com/go-vela/pkg-executor@v0.6.1-0.20201221174708-c434ad8c22a0/executor/linux/api.go:64:9: undefined: syscall.Kill
```
After doing some digging it would appear that the `syscall.Kill()` function does not exist across all OS boundaries.
By switching to using `os.FindProcess()`, this allows the CLI to build as intended.
=> refactor: use os.FindProcess() for compatibility issues

executor/local/local_test.go, executor/local/opts.go, executor/local/opts_test.go
This is a continuation of https://github.com/go-vela/pkg-executor/pull/87
I updated the `go-vela/pkg-executor/executor` package to skip validating specific fields for the `local` executor.
However, I forgot to replicate that for `go-vela/pkg-executor/executor/local` on the client side.
I had to modify some of the tests since they previously expected to receive an error if certain fields weren't set.
They no longer will receive an error since the fields are no longer required.
=> refactor(local): ignore validating client opts

executor/local/build.go, executor/local/build_test.go, executor/local/service.go, executor/local/service_test.go, executor/local/stage.go, executor/local/stage_test.go, executor/local/step.go, executor/local/step_test.go
This removes any calls to the Vela API from the `local` executor.
Currently, running a pipeline on a local workstation and uploading results to the Vela API is considered out of scope.
=> refactor(local): remove API calls

executor/local/build.go, executor/local/service.go, executor/local/stage.go, executor/local/stage_test.go, executor/local/step.go
This updates the `local` executor to output all logs to `stdout` via `fmt.Fprintln(os.Stdout, <message>)`.
Accompanying this, each line of output should have a key setup to indicate what the log is for.
Currently the key patterns are:
* `[service: <service_name>]`
* `[step: <step_name>]`
Here is a sample from the `init` logs I'm running locally:
```
[step: init] > Inspecting runtime network...
[step: init] $ docker network inspect localOrg_localRepo_1
[step: init] {
"Name": "localOrg_localRepo_1",
"Id": "a39d29402f469d828ccaa7de602fe62aaddea5a011379fc38da224cb07aac981",
"Created": "2021-01-13T14:36:49.9474592Z",
"Scope": "local",
"Driver": "bridge",
"EnableIPv6": false,
"IPAM": {
"Driver": "default",
"Options": null, …
```
=> refactor(local): output all logs to stdout

executor/local/build.go, executor/local/service.go, executor/local/stage.go, executor/local/step.go
Removing the "shorthand" variable declarations in the `local` executor.
Throughout the codebase, the first logic of each function is creating short variable declarations:
https://github.com/go-vela/pkg-executor/blob/a5e4076bc95d388ea3d884f7217866c937bc30d3/executor/local/build.go#L24-L27
The problem with this (beyond the extra LOC and variables), is then we are left to update the client with that short variable:
https://github.com/go-vela/pkg-executor/blob/a5e4076bc95d388ea3d884f7217866c937bc30d3/executor/local/build.go#L40
This attempts to make the variable stored in the client the "source of truth" so to speak since we always reference that.
Introducing a consistent `_<resource>` pattern for the `local` executor …
=> refactor(local): update variable configuration

internal/service/load.go, internal/service/load_test.go, internal/step/load.go, internal/step/load_test.go
This adds a check to the `Load()` and `LoadLogs()` functions.
This is important, because we make references to the fields inside the container so if it is `nil`, we get panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14a00e6]
goroutine 574 [running]:
testing.tRunner.func1.1(0x22dd460, 0x30c00b0)
/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc00057ad80)
/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1075 +0x41a
panic(0x22dd460, 0x30c00b0)
/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
github.com/go-vela/pkg-executor/internal/step.LoadLogs(0x0, …
```
=> enhancement(internal): add empty container check

executor/local/build_test.go, executor/local/local.go, executor/local/service.go, executor/local/service_test.go, executor/local/stage_test.go, executor/local/step.go, executor/local/step_test.go
This removes the `serviceLogs` and `stepLogs` fields from the `local` executor client:
https://github.com/go-vela/pkg-executor/blob/384166ec013a3d18b61b5a4bab43a13dbb32c705/executor/local/local.go#L29
https://github.com/go-vela/pkg-executor/blob/384166ec013a3d18b61b5a4bab43a13dbb32c705/executor/local/local.go#L31
These fields are unused since the `local` executor outputs to stdout.
=> chore(local): remove unused logs from client

executor/linux/build.go, executor/linux/secret.go, executor/linux/secret_test.go, executor/linux/service.go, executor/linux/stage.go, executor/linux/stage_test.go, executor/linux/step.go, go.mod
Dependent on https://github.com/go-vela/pkg-executor/pull/95
Removing the "shorthand" variable declarations in the `linux` executor.
Throughout the codebase, the first logic of each function is creating short variable declarations:
https://github.com/go-vela/pkg-executor/blob/384166ec013a3d18b61b5a4bab43a13dbb32c705/executor/linux/build.go#L24-L27
The problem with this (beyond the extra LOC and variables), is then we are left to update the client with that short variable:
https://github.com/go-vela/pkg-executor/blob/384166ec013a3d18b61b5a4bab43a13dbb32c705/executor/linux/build.go#L50
This attempts to make the variable stored in the client the "source of truth" so to speak since we always reference that.
Introducing a …
=> refactor(linux): update variable configuration

executor/linux/build.go, executor/linux/secret.go, executor/linux/stage.go, executor/local/build.go, executor/local/stage.go, go.mod, go.sum
Dependent on https://github.com/go-vela/pkg-runtime/pull/77
This will remove any hardcoded references to inspecting runtime resources which is tracked via the `init` process:
https://github.com/go-vela/pkg-executor/blob/3fbd5e5f77b213f31fbed8f7910b5efaa287e963/executor/linux/build.go#L115-L126
The above code refactored, now looks like:
https://github.com/go-vela/pkg-executor/blob/d084c8258d8e8c30d99f10ee7ca80959e2373ccd/executor/linux/build.go#L114-L124
=> refactor: remove hardcoded inspect commands

executor/linux/secret.go, executor/linux/step.go, executor/local/step.go, internal/step/snapshot.go, internal/step/snapshot_test.go
This adds a new `step.Snapshot()` function to the `go-vela/pkg-executor/internal/step` package.
The intention of this function is to create an instantaneous record of the step and upload it to Vela.
https://github.com/go-vela/pkg-executor/blob/5230079566611352902352b85950588afeb2b930/internal/step/snapshot.go#L17-L69
=> feat(internal): add step.Snapshot() function

executor/linux/service.go, executor/local/service.go, internal/service/snapshot.go, internal/service/snapshot_test.go
This adds a new `service.Snapshot()` function to the `go-vela/pkg-executor/internal/service` package.
The intention of this function is to create an instantaneous record of the service and upload it to Vela.
https://github.com/go-vela/pkg-executor/blob/49441eb159552016029336ad4ebe78800c3f9620/internal/service/snapshot.go#L17-L69
=> feat(internal): add service.Snapshot() function

executor/linux/api.go, executor/local/api.go, executor/local/api_test.go
This implements the API based functions for the `local` executor.
The functions added here are:
* [GetBuild()](https://github.com/go-vela/pkg-executor/blob/29634d7c0d04fca71d141dbd56a30c67f81e6728/executor/local/api.go#L17-L25)
* [GetPipeline()](https://github.com/go-vela/pkg-executor/blob/29634d7c0d04fca71d141dbd56a30c67f81e6728/executor/local/api.go#L27-L35)
* [GetRepo()](https://github.com/go-vela/pkg-executor/blob/29634d7c0d04fca71d141dbd56a30c67f81e6728/executor/local/api.go#L37-L45)
* [CancelBuild()](https://github.com/go-vela/pkg-executor/blob/29634d7c0d04fca71d141dbd56a30c67f81e6728/executor/local/api.go#L47-L69)
=> feat(local): add api executor functions

executor/linux/build.go, executor/linux/stage.go, executor/local/build.go, executor/local/stage.go, internal/step/skip.go, internal/step/skip_test.go
This adds a new `step.Skip()` function to the `go-vela/pkg-executor/internal/step` package.
The intention of this function is to create the ruledata from the llbrary resources and verify the container for the step should be executed.
https://github.com/go-vela/pkg-executor/blob/621ca0a7bb301d3fd403d4a6e67820a97054a1a8/internal/step/skip.go#L15-L46
=> feat(internal): add step.Skip() function

executor/linux/service.go, executor/linux/stage.go, executor/linux/step.go, executor/local/build.go, executor/local/service.go, executor/local/stage.go, executor/local/step.go
This ensures that as the logs are output to `stdout` for the `local` executor, the stage name is also recorded in those logs.
Previously, when running a stages pipeline with the `local` executor, we'd get output like:
```
$ vela exec pipeline --path action/pipeline/testdata --file stages_default.yml
[step: init] > Inspecting runtime network...
[step: init] $ docker network inspect localOrg_localRepo_1
...
```
Now, we get output that looks like this:
```
$ vela exec pipeline --path action/pipeline/testdata --file stages_default.yml
[stage: init][step: init] > Inspecting runtime network...
[stage: init][step: init] $ docker network inspect localOrg_localRepo_1
...
```
I also updated the way we capture service and step …
=> feat(local): add logging pattern for stages

executor/linux/build.go, executor/local/build.go, internal/build/upload.go, internal/build/upload_test.go
This adds a new `build.Upload()` function to the `go-vela/pkg-executor/internal/build` package.
The intention of this function is to track the final state of the build and upload it to Vela.
https://github.com/go-vela/pkg-executor/blob/e93ba33c7f6ab785fa56f7ae565a8addc56644d5/internal/build/upload.go#L16-L72
=> feat(internal): add build.Upload() function

executor/linux/service.go, executor/local/service.go, internal/service/upload.go, internal/service/upload_test.go
This refactors the `service.Snapshot()` function to `service.Upload()` for the `go-vela/pkg-executor/internal/service` package.
The `service.Snapshot()` function was already tracking the final state of the service and uploading it to Vela.
Renaming it to `service.Upload()` will keep it in sync with the `internal/build` package and follow the upload pattern.
A `service.Snapshot()` function will be added in a subsequent PR that fits better with the snapshot pattern.
https://github.com/go-vela/pkg-executor/blob/67d59a9a841dde61d8a52d101440187e6bbdce66/internal/service/upload.go#L17-L88
=> refactor: service.Snapshot() -> service.Upload()

executor/executor_test.go, executor/linux/linux.go, executor/linux/opts.go, executor/linux/opts_test.go, executor/linux/secret.go, executor/linux/service.go, executor/linux/step.go, executor/local/local.go, executor/local/opts.go, executor/local/opts_test.go, executor/local/service.go, executor/local/step.go, executor/setup.go, executor/setup_test.go, internal/service/environment.go, internal/service/environment_test.go, internal/step/environment.go, internal/step/environment_test.go
This allows us to pass a version to the executor clients so we no longer have to hardcode these values.
Currently we have code that looks like this:
https://github.com/go-vela/pkg-executor/blob/e5c5b0b461bb681bbd47e39c8276d9f6ad275399/internal/service/environment.go#L46-L47
https://github.com/go-vela/pkg-executor/blob/e5c5b0b461bb681bbd47e39c8276d9f6ad275399/internal/step/environment.go#L46-L47
https://github.com/go-vela/pkg-executor/blob/e5c5b0b461bb681bbd47e39c8276d9f6ad275399/executor/linux/secret.go#L49-L50
The problem with this is we are left responsible to update the code when any new release is created allowing for the potential of having inaccurate information in the codebase if the code is not updated.
By …
=> feat(executor): enable setting executor version

executor/linux/build.go, executor/linux/stage.go, executor/linux/step.go, executor/local/build.go, executor/local/stage.go, executor/local/step.go, internal/step/snapshot.go, internal/step/snapshot_test.go
See https://github.com/go-vela/pkg-executor/pull/108 for reference
This adds a new `step.Snapshot()` function to the `go-vela/pkg-executor/internal/step` package.
The intention of this function is to create an instantaneous record of the step and upload it to Vela.
https://github.com/go-vela/pkg-executor/blob/898c9d1d0bbf7d5e4fdbb3c8466a73e86f7e0863/internal/step/snapshot.go#L17-L57
=> feat(internal): add step.Snapshot() function v2

executor/linux/service.go, executor/local/service.go, internal/service/snapshot.go, internal/service/snapshot_test.go
See https://github.com/go-vela/pkg-executor/pull/109 for reference
This adds a new `service.Snapshot()` function to the `go-vela/pkg-executor/internal/service` package.
The intention of this function is to create an instantaneous record of the service and upload it to Vela.
https://github.com/go-vela/pkg-executor/blob/598f6a177ba0ed4c78635640fa731e486a8ecdb6/internal/service/snapshot.go#L17-L57
=> feat(internal): add service.Snapshot() function v2

executor/linux/build.go, executor/local/build.go
This updates the logic in the `AssembleBuild()` function to use `step.Upload()`.
This allows us to adopt and follow the same pattern we use for tracking and uploading the state for the other steps.
=> refactor: use step.Upload() for the init step

executor/local/build_test.go, executor/local/service_test.go, executor/local/stage_test.go, executor/local/step_test.go
This refactors the tests we have setup for the `go-vela/pkg-executor/executor/local` package.
The test coverage went from `87.4%` to `89.9%` and the time to execute went from ~ `16s` to ~ `6s`
You'll also note that the total number of LOC for the tests was cut in half.
These are the results of test coverage on the `master` branch:
```sh
$ make test-cover
?   	github.com/go-vela/pkg-executor/cmd/vela-executor	[no test files]
ok  	github.com/go-vela/pkg-executor/executor	0.570s	coverage: 100.0% of statements
ok  	github.com/go-vela/pkg-executor/executor/linux	18.602s	coverage: 83.4% of statements
ok  	github.com/go-vela/pkg-executor/executor/local	15.998s	coverage: 87.4% of statements
? …
```
=> test(local): overhaul test suite

executor/local/step.go, executor/local/step_test.go
I was playing around with the CLI locally trying to run pipelines on my workstation.
I noticed that when I was running certain pipelines that I would get the output for `stages` when I shouldn't be.
Here is the pipeline I was using:
```yaml
version: "1"
steps:
- name: echo
image: alpine:latest
commands:
- echo hello
```
Before this PR, the output looks like this:
```sh
[stage: ][step: echo] $ echo hello
[stage: ][step: echo] hello
```
Now, the output looks like this:
```sh
[step: echo] $ echo hello
[step: echo] hello
```
=> fix(local): step output for stages

executor/linux/build.go, executor/linux/service.go, executor/linux/step.go, executor/local/build.go, executor/local/service.go, executor/local/step.go
This fixes a bug with the manipulation of variables stored in the client that are passed to the `defer` calls.
Per https://golang.org/doc/effective_go.html#defer:
> The arguments to the deferred function (which include the receiver if the function is a method) are evaluated when the _defer_ executes, not when the _call_ executes. Besides avoiding worries about variables changing values as the function executes, this means that a single deferred call site can defer multiple function executions.
Due to the arguments for a deferred function being evaluated at the time the `defer` executes, this means that any manipulation of those variables after the `defer` are "ignored" for lack of a better term.
As an example, we pass …
=> fix: wrap defers in function shell

executor/linux/build.go, executor/linux/step.go, executor/local/build.go, executor/local/step.go, internal/step/load.go, internal/step/load_test.go
This adds a new `step.LoadInit()` function to the `go-vela/pkg-executor/internal/step` package.
The intention of this function is to load the `init` process into the executor client from the pipeline.
https://github.com/go-vela/pkg-executor/blob/1024fe8e5af1b7bdabbb73f0a2326bd37abfde85/internal/step/load.go#L38-L62
=> feat(internal): add step.LoadInit() function

executor/linux/api.go, executor/local/api.go, internal/build/snapshot.go, internal/build/upload.go
Fixes https://github.com/go-vela/community/issues/200
A bug was introduced in https://github.com/go-vela/pkg-executor/pull/107 that prevented builds from being in a `canceled` status.
Originally this was accomplished with https://github.com/go-vela/pkg-executor/pull/51 and https://github.com/go-vela/pkg-executor/pull/54
This creates confusion for end users who are attempting to cancel a build and reviewing their build history.
We now will check to see if the build is in a `canceled` status before attempting to populate any error messages.
=> fix(internal): ignore build errors in canceled state

executor/linux/service.go, executor/linux/step.go, executor/local/service.go, executor/local/step.go
Currently, if you run a `stages` pipeline that has a step with `detach: true`, you'll see an error message like:
```
unable to copy logs for container: context canceled
```
This error is present with both the `linux` and `local` executors.
The error message is actually coming from the [go-vela/pkg-runtime](https://github.com/go-vela/pkg-runtime/blob/a5f1d7965395afc253994a2954e7f0709020c9e3/runtime/docker/container.go#L253) codebase.
This happens because the context we pass when streaming logs is timing out.
This fix will always pass a fresh context (`context.Background()`) when we attempt to stream logs.
Here is an example pipeline:
```yaml
version: "1"
services:
- name: mongo
image: mongo:latest
stages:
redis:
steps:
- name: redis
image: redis:latest
detach: true
- name: check status …
```
=> fix: use fresh context for capturing container logs

executor/linux/api.go, executor/local/api.go
Fixes https://github.com/go-vela/community/issues/201
Sending a SIGTERM to cancel the executor actually terminates the entire worker. In the future Go may support separate PIDs per thread https://github.com/golang/go/issues/19326
=> fix(cancel): remove SIGTERM in favor of executor.DestroyBuild

go.mod, go.sum
This pulls in the latest changes for the [go-vela/pkg-runtime](https://github.com/go-vela/pkg-runtime) codebase.
The primary focus is to address the bug resolved with https://github.com/go-vela/pkg-runtime/pull/114
=> chore: upgrade go-vela/pkg-runtime on latest

go.mod, go.sum
Related to https://github.com/go-vela/pkg-runtime/pull/115
This is a backport of https://github.com/go-vela/pkg-runtime/pull/114 for the `v0.7.x` release.
This pulls in the `v0.7.5` tag for the [go-vela/pkg-runtime](https://github.com/go-vela/pkg-runtime) codebase.
=> chore: upgrade go-vela/pkg-runtime on v0.7.5

go.mod, go.sum
Dependency updates needed for https://github.com/go-vela/types/pull/175
=> chore: update dependencies for types pr 175

executor/linux/secret.go, executor/linux/secret_test.go, executor/linux/step.go
Fixes: https://github.com/go-vela/community/issues/75
This PR replaces all instances of `\\n` with `\\\n` within a secret and ensures that newlines within secrets are preserved when they are used within a pipeline.
This should _skip_ escaping newlines for secrets where users have manually escaped newlines
https://github.com/go-vela/pkg-executor/blob/8382d080d029e7acce0d2c7a9e6865b8137b1466/executor/linux/secret.go#L362
When secrets are injected into a pipeline, newlines are escaped (`\n` -> `\\n`), but when the types method [container.Substitute](https://github.com/go-vela/types/blob/62027576a4adda164c848c205d9ba2f08bae1178/pipeline/container.go#L289) is called from executor, [envsubst.Eval(string(body), subFunc)](https://github.com/go-vela/types/blob/62027576a4adda164c848c205d9ba2f08bae11 …
=> fix: escape \\n in secrets

executor/flags.go
This adds support for the `github.com/go-vela/pkg-executor/executor.Flags{}` to be set via files.
The syntax for the path to these files is:
```sh
/vela/executor/<parameter>
```
Using the `executor.driver` flag as an example:
```sh
/vela/executor/driver
```
=> feat(executor): support configuration from file paths

executor/engine.go, executor/linux/build.go, executor/linux/secret.go, executor/linux/stage.go, executor/linux/stage_test.go, executor/local/build.go, executor/local/stage.go, executor/local/stage_test.go
fixes: https://github.com/go-vela/community/issues/342
i was able to reproduce the issue by constraining the resources in the supplied `docker-compose.yml` for the `worker` service on my local machine:
```yaml
worker:
deploy:
resources:
limits:
cpus: '0.50'
memory: 10M
```
then, i crafted a pipeline (`.vela.star`) as follows:
```starlark
def create_stages(n):
s = {}
for i in range(1, n): 
s["stage_" + str(i)] = {
"steps": [
{
"name": "echo-step-for-stage-" + str(i),
"image": "alpine:latest",
"commands": [
"echo hello from stage " + str(i),
"sleep 5",
"echo done"
]
}
]
}
return s
def main(ctx):
return {
'version': '1',
'stages': create_stages(100)
}
```
the pipeline creates 100 stages with one identical step. this resulted in the unsafe concurrent map access in about 80% of builds which …
=> fix: use sync.Map for concurrent access
